### ISSUE TITLE
Deploy compiled slides

### ISSUE THREAD

**Issue by HaNdTriX** [farbenmeer/ausguck#8]
A. Use Github releases
B. Use pdf`s
C. Both

**Comment by mstruebing** [comment]
https://help.github.com/categories/github-pages-basics/

**Comment by Tobi-mmt** [comment]
@mstruebing i have no permissions to edit the settings of this repo. So I can't enable github pages

**Comment by mstruebing** [comment]
Same here :+1:

**Comment by Tobi-mmt** [comment]
@pex @Kampfheizung admin anyone?

**Comment by mstruebing** [comment]
@Flaxxas maybe?

**Comment by Flaxxas** [comment]
Nope.. We have some strict hierarchy at farbenmeer 😉

**Comment by Kampfheizung** [comment]
Now everyone inside the ensemble group has admin privileges 👍 "CTO" has spoken

**Comment by Tobi-mmt** [comment]
https://codeburst.io/deploy-react-to-github-pages-to-create-an-amazing-website-42d8b09cd4d

**Comment by Tobi-mmt** [comment]
resolved with PR #12
